<?php
/**
 * Created by PhpStorm.
 * User: hahastein
 * Date: 2018/9/24
 * Time: 0:14
 */

namespace bengbeng\admin\controllers;

use bengbeng\admin\base\BaseController;
use bengbeng\admin\components\handles\TemplateHandle;
use bengbeng\admin\models\setting\ARSettingPage;
use bengbeng\framework\base\data\ActiveOperate;
use Yii;
use bengbeng\admin\models\form\AdminLogin;
use bengbeng\framework\base\Enum;
use yii\db\ActiveQuery;

class AuthController extends BaseController
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = '@bengbeng/admin/views/'.TemplateHandle::getTheme().'/layout/login';
    }

    public function actionLogin()
    {

        $cache_name = 'template_'.md5('auth/login');
        $cache = \Yii::$app->cache;
        if(!$cache->exists($cache_name)){
            $settingPage = new ARSettingPage();
            $pageData = $settingPage->dataOne(function (ActiveQuery $query){
                $query->select(['title', 'template_id', 'last_time', 'resource_file', 'css_order']);
                $query->where([
                    'router' => 'auth/login'
                ]);
                $query->asArray();
            });
            $cache->add($cache_name, $pageData);
        }

        if (!Yii::$app->getUser()->isGuest) {
            return $this->goHome();
        }

        $model = new AdminLogin();
        if ($model->load(Yii::$app->getRequest()->post())) {
            if($model->login()){
                return $this->goHome();
            }else{
//                $errors = current($model->getFirstErrors());
                return $this->renderAjax('login', [
                    'model' => $model,
                ]);
            }
        } else {
            return $this->render('login', ['model' => $model]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goBack(['system/auth/login']);
    }

    public function behaviors()
    {
        self::setActions([
            'login'
        ], Enum::ACCESS_RULE_NULL);
        self::setActions([
            'logout'
        ]);
        return parent::behaviors();
    }

}