<?php
/**
 * Created by PhpStorm.
 * User: hahastein
 * Date: 2018/9/24
 * Time: 0:14
 */

namespace bengbeng\admin\controllers;

use bengbeng\admin\base\BaseController;
use bengbeng\admin\components\handles\TemplateHandle;
use bengbeng\admin\models\setting\ARSettingPage;
use bengbeng\framework\base\data\ActiveOperate;
use Yii;
use bengbeng\admin\models\form\AdminLogin;
use bengbeng\framework\base\Enum;

class AuthController extends BaseController
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = '@bengbeng/admin/views/'.TemplateHandle::getTheme().'/layout/login';
    }

    public function actionLogin()
    {


        $resource = [
            'js' => [
                'pages/login.js',
            ],
            'css' => [
                'pages/login-register-lock.css'
            ],
        ];

        //拼接数据
        $dataParam = [
            'title' => '登录页面资源',
            'template_id' => 1,
            'last_time' => time(),
            'resource_file' => serialize($resource),
            'css_order' => 1
        ];

        $settingPage = new ARSettingPage();
        if($settingPage->dataUpdate(function (ActiveOperate $operate) use ($dataParam){
            $operate->params($dataParam);
            $operate->where([
                'router' => 'auth/login'
            ]);
        })){
            //更新缓存
            $cache_name = 'template_'.md5('auth/login');
            $cache = \Yii::$app->cache;
            if($cache->exists($cache_name)){
                $cache->set($cache_name, $dataParam);
            }else{
                $cache->add($cache_name, $dataParam);
            }


        }else{
            \Yii::$app->Beng->outHtml('更新失败');

        }


        if (!Yii::$app->getUser()->isGuest) {
            return $this->goHome();
        }

        $model = new AdminLogin();
        if ($model->load(Yii::$app->getRequest()->post())) {
            if($model->login()){
                return $this->goHome();
            }else{
//                $errors = current($model->getFirstErrors());
                return $this->renderAjax('login', [
                    'model' => $model,
                ]);
            }
        } else {
            return $this->render('login', ['model' => $model]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goBack(['system/auth/login']);
    }

    public function behaviors()
    {
        self::setActions([
            'login'
        ], Enum::ACCESS_RULE_NULL);
        self::setActions([
            'logout'
        ]);
        return parent::behaviors();
    }

}