<?php

namespace bengbeng\admin\controllers;

use bengbeng\admin\base\AdminBaseController;
use bengbeng\admin\logic\menu\MenuBLL;
use bengbeng\admin\models\menu\ARMenu;
use bengbeng\framework\base\Enum;
use bengbeng\framework\models\platform\MenuARModel;
use Yii;
use yii\db\ActiveQuery;
use yii\db\Exception;
use yii\helpers\ArrayHelper;

/**
 * MenuController implements the CRUD actions for Menu model.
 *
 * @author hahastein <146119@qq.com>
 * @since 1.0
 */
class MenuController extends AdminBaseController
{

    protected $actionPower = ['save', 'update-cache'];

    /**
     * @var MenuBLL
     */
    private $logic;

    public function init()
    {
        $this->logic = $this->getLogicLayer('menu.MenuBLL');
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionAll(){
        $this->renderData = $this->logic->getList();
    }

    public function actionSave(){

        $postData = \Yii::$app->Beng->PostData([
            'menu_name' => 'menuName',
            'controller','action','menu_icon','initials',
            'parent_id' => 'parentMenu'
        ]);

        $this->renderType = $this->logic->save($postData);
        $this->renderData = $this->logic->getMessage();

    }

    public function actionUpdateCache(){

    }
}
