<?php
/**
 * Created by PhpStorm.
 * User: gameg
 * Date: 2019/3/13
 * Time: 16:27
 */

namespace bengbeng\admin\widgets;


use bengbeng\admin\components\handles\TemplateHandle;
use yii\base\Widget;

class BaseWidget extends Widget
{
    public function render($view, $params = [])
    {
        if(strpos($view, '@') === false){
            $view = '@bengbeng/admin/views/'.TemplateHandle::getTheme().'/widgets/'. $view;
        }
        return parent::render($view, $params); // TODO: Change the autogenerated stub
    }
}