<?php
/**
 * Created by PhpStorm.
 * User: hahastein
 * Date: 2018/10/16
 * Time: 23:49
 */

namespace bengbeng\admin\components\assets;


use bengbeng\admin\base\BaseAssetBundle;

class PluginsAsset extends BaseAssetBundle
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->sourcePath .= "plugins" . DIRECTORY_SEPARATOR;
    }

    public static function register($view, $plus = null)
    {
        foreach ($plus as $item){
            $this->js
        }
        return parent::register($view); // TODO: Change the autogenerated stub
    }

}