<?php
/**
 * Created by PhpStorm.
 * User: hahastein
 * Date: 2018/11/10
 * Time: 2:16
 */

namespace bengbeng\admin\widgets\information;

use bengbeng\admin\components\handles\TemplateHandle;
use yii\base\Widget;

class ToolTips extends Widget
{

    public $msg_open = true;
    public $alert_open = true;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('@bengbeng/admin/views/'.TemplateHandle::getTheme().'/widgets/tooltips', [
            'msg' => $this->msg_open,
            'alert' => $this->alert_open
        ]);
    }
}